name: Publish to GitHub Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
        tag:
          description: 'Release tag (e.g. v1.2.3)'
          required: true

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      RELEASE_TAG: ${{ github.event_name == 'workflow_dispatch' && inputs.tag || github.ref_name }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: build SDK
        # we use debug as otherwise we get the nuget stuff we don't want.
        run: |
          git clone https://github.com/VedalAI/neuro-sdk.git
          ls
          cd neuro-sdk
          echo "in neuro sdk"
          ls
          git fetch --all
          git branch -r
          git checkout origin/inline-nativewebsocket
          cd Unity/NuGet
          dotnet publish NeuroSdk.csproj -c Debug -o out

      - name: list home
        run: ls ~

      - name: Create lib folder
        run: |
          pwd
          mkdir NeuroTFWRIntegration/lib

      - name: move SDK
        run: |
         cp neuro-sdk/Unity/NuGet/out/NeuroSdk.dll NeuroTFWRIntegration/lib/

      - name: print lib
        run: ls NeuroTFWRIntegration/lib

      - name: build
        run: |
          cd NeuroTFWRIntegration
          dotnet build NeuroTFWRIntegration.csproj -c Release -o out

      - name: public release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create $RELEASE_TAG NeuroTFWRIntegration/out/*.dll