name: Publish to GitHub Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
        tag:
          description: 'Release tag (e.g. v1.2.3)'
          required: true

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      RELEASE_TAG: ${{ github.event_name == 'workflow_dispatch' && inputs.tag || github.ref_name }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # we need to do this as the SDK and the game share a class name and when compiling it likes to pick the game's class rather than the SDK's for some reason.
      - name: build SDK
        # we use debug as otherwise we get the nuget stuff we don't want.
        run: |
          git clone https://github.com/VedalAI/neuro-sdk.git
          cd neuro-sdk
          git fetch --all
          cd Unity/NuGet
          dotnet publish NeuroSdk.csproj -c Debug -o out

      - name: Create lib folder
        run: |
          pwd
          mkdir NeuroTFWRIntegration/lib

      - name: move SDK
        run: |
         cp neuro-sdk/Unity/NuGet/out/NeuroSdk.dll NeuroTFWRIntegration/lib/

      - name: build
        run: |
          cd NeuroTFWRIntegration
          dotnet publish NeuroTFWRIntegration.csproj -c Release -o out

      - name: public release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          cd NeuroTFWRIntegration
          mkdir NeuroTFWRIntegration
          cp out/NeuroTFWRIntegration.dll NeuroTFWRIntegration/
          cp out/Newtonsoft.Json.dll NeuroTFWRIntegration/
          cp out/NeuroSdk.dll NeuroTFWRIntegration/
          cp out/EditParsing.dll NeuroTFWRIntegration/
          zip -r NeuroTFWRIntegration.zip NeuroTFWRIntegration

          gh release create "$RELEASE_TAG" NeuroTFWRIntegration.zip
