name: Publish to GitHub Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
        tag:
          description: 'Release tag (e.g. v1.2.3)'
          required: true

permissions:
  contents: write

jobs:
  run-editor-script:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v3
        with:
          path: UnityProjects/NeuroTFWRIntegrationUnity/Library
          key: UnityProjects/NeuroTFWRIntegrationUnity/Library-${{ hashFiles('Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            UnityProjects/NeuroTFWRIntegrationUnity/Library-

      - uses: game-ci/unity-builder@v4
        # this doesn't work locally
        if: ${{ github.actor != 'nektos/act' }}
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          allowDirtyBuild: true

          projectPath: UnityProjects/NeuroTFWRIntegrationUnity
          buildPath: 'build/StandaloneWindows64'
          buildName: 'StandaloneWindows64'
          targetPlatform: StandaloneWindows64
          unityVersion: '6000.0.43f1'
          buildMethod: Editor.BuildAssetBundles.BuildAllAssetBundles

      - name: Upload asset bundles
        uses: actions/upload-artifact@v4
        with:
          name: asset-bundles
          path: UnityProjects/NeuroTFWRIntegrationUnity/AssetBundles/

  build-and-publish:
    needs: run-editor-script
    runs-on: ubuntu-latest
    env:
      RELEASE_TAG: ${{ github.event_name == 'workflow_dispatch' && inputs.tag || github.ref_name }}

    steps:
      - uses: actions/checkout@v4

      - name: Download asset bundles
        uses: actions/download-artifact@v4
        with:
          name: asset-bundles
          path: asset-bundles

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # we need to do this as the SDK and the game share a class name and when compiling it likes to pick the game's class rather than the SDK's for some reason.
      - name: build SDK
        # we use debug as otherwise we get the nuget stuff we don't want.
        run: |
          git clone https://github.com/VedalAI/neuro-sdk.git
          cd neuro-sdk
          git fetch --all
          cd Unity/NuGet
          dotnet publish NeuroSdk.csproj -c Debug -o out

      - name: Create lib folder
        run: |
          pwd
          mkdir NeuroTFWRIntegration/lib

      - name: move SDK
        run: |
         cp neuro-sdk/Unity/NuGet/out/NeuroSdk.dll NeuroTFWRIntegration/lib/

      - name: build
        run: |
          cd NeuroTFWRIntegration
          dotnet publish NeuroTFWRIntegration.csproj -c Release -o out

      - name: public release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          cd NeuroTFWRIntegration

          mkdir -p NeuroTFWRIntegration/AssetBundles

          cp out/NeuroTFWRIntegration.dll NeuroTFWRIntegration/
          cp out/Newtonsoft.Json.dll NeuroTFWRIntegration/
          cp out/NeuroSdk.dll NeuroTFWRIntegration/
          cp out/EditParsing.dll NeuroTFWRIntegration/

          cp -r ../asset-bundles/* NeuroTFWRIntegration/AssetBundles/

          zip -r NeuroTFWRIntegration.zip NeuroTFWRIntegration
          gh release create "$RELEASE_TAG" -F ../release-notes.md NeuroTFWRIntegration.zip

