name: Publish to GitHub Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
        tag:
          description: 'Release tag (e.g. v1.2.3)'
          required: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      RELEASE_TAG: ${{ github.event_name == 'workflow_dispatch' && inputs.tag || github.ref_name }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Move home
        run: cd ~
      # TODO: I have a look and compiling the Neuro-Sdk from source could work.
      - name: Clone SDK
        run: git clone https://github.com/VedalAI/neuro-sdk.git

      - name: enter
        run: cd neuro-sdk

      - name: change branch
        run: git checkout inline-nativewebsocket

      - name: enter SDK
        run: cd neuro-sdk/Unity/NuGet

      - name: restore SDK
        run: dotnet restore NeuroSdk.csproj

      - name: build SDK
        # we use debug as otherwise we get the nuget stuff we don't want.
        run: dotnet publish NeuroSdk.csproj -c Debug -o out

      - name: Create lib folder
        run: mkdir ~/NeuroTFWRIntegration/lib

      - name: move SDK
        run: cp out/NeuroSdk.dll ~/NeuroTFWRIntegration/lib/

      - name: Move home
        run: cd ~/NeuroTFWRIntegration
      # - name: restore
      #   run: dotnet restore

      - name: build
        run: dotnet publish NeuroTFWRIntegration/NeuroTFWRIntegration.csproj -c Release -o out

      # - name: test
      #   run: dotnet test -c Release --no-build --verbosity normal

      - name: public release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create $RELEASE_TAG out/*.dll